
package vistas;

import controladores.AlumnoData;
import controladores.InscripcionData;
import controladores.MateriaData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.Inscripcion;
import modelo.Materia;

/**
 *
 * @author VIB
 */
public class VistaCargarNota extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private Inscripcion inscripcion = new Inscripcion();
    private InscripcionData inscripcionD = new InscripcionData();
    private AlumnoData alumnoD = new AlumnoData();
    private Materia materia = new Materia();
    private ArrayList<Inscripcion> inscriptos = new ArrayList();
    private ArrayList<Alumno> alumnos = new ArrayList();
    private ArrayList<Materia> materias = new ArrayList();

    /**
     * Creates new form VistaCargarNota
     */
    public VistaCargarNota() {
        initComponents();
        alumnos = alumnoD.listarAlumnos();
        encabezado();
        llenarComboBox();
    }
     private void llenarComboBox(){
        for(Alumno a: alumnos){
            cBAlumnos.addItem(a);
        }
    }
      private void borrarFilas(){
        int fila = modeloTabla.getRowCount()-1;
        for(int i=fila; i>=0;i--){
            modeloTabla.removeRow(i);
        }
    }
       
    private void encabezado(){
        ArrayList<Object> columna = new ArrayList();
        columna.add("Código");
        columna.add("Nombre");
        columna.add("Nota");
        for(Object c: columna){
            modeloTabla.addColumn(c);
        }
        jTablaNotas.setModel(modeloTabla);
    }
    private void llenarTabla(){
        borrarFilas();
        Alumno seleccionado =(Alumno)cBAlumnos.getSelectedItem();
        inscriptos = inscripcionD.obtenerInscripcionXAlumno(seleccionado.getId());
        for(Inscripcion i:inscriptos){
           modeloTabla.addRow(new Object[]{i.getMateria().getId_materia(),i.getMateria().getNombre(),i.getNota()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cBAlumnos = new javax.swing.JComboBox<>();
        jSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaNotas = new javax.swing.JTable();
        jGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jNota = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Cargar Notas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("ALUMNO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 68, -1, -1));

        cBAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(cBAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 63, 220, 30));

        jSalir.setBackground(new java.awt.Color(0, 102, 102));
        jSalir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jSalir.setForeground(new java.awt.Color(255, 255, 255));
        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 93, -1));

        jTablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablaNotas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 105, 374, 227));

        jGuardar.setBackground(new java.awt.Color(0, 102, 102));
        jGuardar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jGuardar.setText("Guardar");
        jGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Ingrese la nueva nota:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));
        getContentPane().add(jNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 141, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cBAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBAlumnosActionPerformed
       borrarFilas();
       llenarTabla();
    }//GEN-LAST:event_cBAlumnosActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    private void jGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTablaNotas.getSelectedRow();
        if (filaSeleccionada != -1){
            Alumno seleccionado =(Alumno)cBAlumnos.getSelectedItem();
            int idMateria = (Integer)modeloTabla.getValueAt(filaSeleccionada, 0);
            double nota1 = Double.parseDouble(jNota.getText());
            inscripcionD.actualizarNota(seleccionado.getId(),idMateria, nota1);
        } else {
            JOptionPane.showMessageDialog(null,"Debe seleccionar una materia");
        }
    }//GEN-LAST:event_jGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> cBAlumnos;
    private javax.swing.JButton jGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jNota;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaNotas;
    // End of variables declaration//GEN-END:variables
}
