
package vistas;

import controladores.AlumnoData;
import controladores.InscripcionData;
import controladores.MateriaData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.Inscripcion;
import modelo.Materia;

/**
 *
 * @author VIB
 */
public class VistaCargarNota extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private Inscripcion inscripcion = new Inscripcion();
    private InscripcionData inscripcionD = new InscripcionData();
    private AlumnoData alumnoD = new AlumnoData();
    private Materia materia = new Materia();
    private ArrayList<Inscripcion> inscriptos = new ArrayList();
    private ArrayList<Alumno> alumnos = new ArrayList();
    private ArrayList<Materia> materias = new ArrayList();

    /**
     * Creates new form VistaCargarNota
     */
    public VistaCargarNota() {
        initComponents();
        alumnos = alumnoD.listarAlumnos();
        encabezado();
        llenarComboBox();
    }
     private void llenarComboBox(){
        for(Alumno a: alumnos){
            cBAlumnos.addItem(a);
        }
    }
      private void borrarFilas(){
        int fila = modeloTabla.getRowCount()-1;
        for(int i=fila; i>=0;i--){
            modeloTabla.removeRow(i);
        }
    }
       
    private void encabezado(){
        ArrayList<Object> columna = new ArrayList();
        columna.add("Código");
        columna.add("Nombre");
        columna.add("Nota");
        for(Object c: columna){
            modeloTabla.addColumn(c);
        }
        jTablaNotas.setModel(modeloTabla);
    }
    private void llenarTabla(){
        borrarFilas();
        Alumno seleccionado =(Alumno)cBAlumnos.getSelectedItem();
        inscriptos = inscripcionD.obtenerInscripcionXAlumno(seleccionado.getId());
        for(Inscripcion i:inscriptos){
           modeloTabla.addRow(new Object[]{i.getMateria().getId_materia(),i.getMateria().getNombre(),i.getNota()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cBAlumnos = new javax.swing.JComboBox<>();
        jSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaNotas = new javax.swing.JTable();
        jGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jNota = new javax.swing.JTextField();

        jLabel1.setText("Cargar Notas");

        jLabel4.setText("ALUMNO");

        cBAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBAlumnosActionPerformed(evt);
            }
        });

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jTablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablaNotas);

        jGuardar.setText("Guardar");
        jGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese la nueva nota:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jGuardar)))
                        .addGap(127, 127, 127)
                        .addComponent(jSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(jNota, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(56, 56, 56)
                        .addComponent(cBAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGuardar)
                    .addComponent(jSalir)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cBAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBAlumnosActionPerformed
       borrarFilas();
       llenarTabla();
    }//GEN-LAST:event_cBAlumnosActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    private void jGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTablaNotas.getSelectedRow();
        if (filaSeleccionada != -1){
            Alumno seleccionado =(Alumno)cBAlumnos.getSelectedItem();
            int idMateria = (Integer)modeloTabla.getValueAt(filaSeleccionada, 0);
            double nota1 = Double.parseDouble(jNota.getText());
            inscripcionD.actualizarNota(seleccionado.getId(),idMateria, nota1);
        } else {
            JOptionPane.showMessageDialog(null,"Debe seleccionar una materia");
        }
    }//GEN-LAST:event_jGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> cBAlumnos;
    private javax.swing.JButton jGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jNota;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaNotas;
    // End of variables declaration//GEN-END:variables
}
