
package vistas;

import controladores.AlumnoData;
import controladores.InscripcionData;
import controladores.MateriaData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.Inscripcion;
import modelo.Materia;

/**
 *
 * @author Giulietta
 */
public class VistasInscripciones extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private Inscripcion inscripcion = new Inscripcion();
    private InscripcionData inscripcionD = new InscripcionData();
    private AlumnoData alumnoD = new AlumnoData();
    private Materia materia = new Materia();
    private MateriaData materiaD = new MateriaData();
    private ArrayList<Inscripcion> inscriptos = new ArrayList();
    private ArrayList<Inscripcion> noinscriptos = new ArrayList();
    private ArrayList<Alumno> alumnos = new ArrayList();
    private ArrayList<Materia> materias = new ArrayList();
    /**
     * Creates new form VistasInscripciones
     */
    public VistasInscripciones() {
        initComponents();
        alumnos = alumnoD.listarAlumnos();
        encabezado();
        llenarComboBox();
    } 
    
    private void llenarComboBox(){
        for(Alumno a: alumnos){
            cBAlumnos.addItem(a);
        }
    }
    
    private void encabezado(){
        ArrayList<Object> columna = new ArrayList();
        columna.add("Código");
        columna.add("Nombre");
        columna.add("Año");
        for(Object c: columna){
            modeloTabla.addColumn(c);
        }
        jTablaMaterias.setModel(modeloTabla);
    }
    private void llenarTabla(){
        borrarFilas();
        Alumno seleccionado =(Alumno)cBAlumnos.getSelectedItem();
        if(jInscriptos.isSelected() == true){
            materias = inscripcionD.obtenerMateriasCursadas(seleccionado.getId());
            for(Materia a:materias){
            modeloTabla.addRow(new Object[]{a.getId_materia(),a.getNombre(),a.getAnio()});
            }
        }
        if(jNoInscriptas.isSelected() == true){
            materias = inscripcionD.obtenerMateriasNOCursadas(seleccionado.getId());
            for(Materia a:materias){
            modeloTabla.addRow(new Object[]{a.getId_materia(),a.getNombre(),a.getAnio()});
            }
        }
        
        
        
    }
    
    private void borrarFilas(){
        int fila = modeloTabla.getRowCount()-1;
        for(int i=fila; i>=0;i--){
            modeloTabla.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cBAlumnos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jInscriptos = new javax.swing.JRadioButton();
        jNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaMaterias = new javax.swing.JTable();
        jInscribir = new javax.swing.JButton();
        jAnular = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setMaximumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(450, 450));

        jSalir.setBackground(new java.awt.Color(0, 102, 102));
        jSalir.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jSalir.setForeground(new java.awt.Color(255, 255, 255));
        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Formulario de inscripción");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("ALUMNO");

        cBAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBAlumnosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("LISTADO DE MATERIAS");

        jInscriptos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jInscriptos.setForeground(new java.awt.Color(0, 102, 102));
        jInscriptos.setText("Inscriptas");
        jInscriptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInscriptosActionPerformed(evt);
            }
        });

        jNoInscriptas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jNoInscriptas.setForeground(new java.awt.Color(0, 102, 102));
        jNoInscriptas.setText("No Inscriptas");
        jNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoInscriptasActionPerformed(evt);
            }
        });

        jTablaMaterias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablaMaterias);

        jInscribir.setBackground(new java.awt.Color(0, 102, 102));
        jInscribir.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jInscribir.setForeground(new java.awt.Color(255, 255, 255));
        jInscribir.setText("Inscribir");
        jInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInscribirActionPerformed(evt);
            }
        });

        jAnular.setBackground(new java.awt.Color(0, 102, 102));
        jAnular.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jAnular.setForeground(new java.awt.Color(255, 255, 255));
        jAnular.setText("Anular Inscripcion");
        jAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(cBAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jInscriptos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jNoInscriptas)
                                .addGap(33, 33, 33))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jInscribir)
                                .addGap(65, 65, 65)
                                .addComponent(jAnular)
                                .addGap(69, 69, 69)
                                .addComponent(jSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInscriptos)
                    .addComponent(jNoInscriptas))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInscribir)
                    .addComponent(jAnular)
                    .addComponent(jSalir))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        dispose();

    }//GEN-LAST:event_jSalirActionPerformed

    private void cBAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBAlumnosActionPerformed
        jInscriptos.setSelected(false);
        jNoInscriptas.setSelected(false);
        jInscribir.setEnabled(false);
        jAnular.setEnabled(false);
        borrarFilas();
    }//GEN-LAST:event_cBAlumnosActionPerformed

    private void jNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoInscriptasActionPerformed
        jInscribir.setEnabled(true);
        jAnular.setEnabled(false);
        jInscriptos.setSelected(false);
        llenarTabla();
    }//GEN-LAST:event_jNoInscriptasActionPerformed

    private void jInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInscribirActionPerformed
        int filaSeleccionada = jTablaMaterias.getSelectedRow();
        if (filaSeleccionada != -1){
            Alumno seleccionado =(Alumno)cBAlumnos.getSelectedItem();
            int idMateria = (Integer)modeloTabla.getValueAt(filaSeleccionada, 0);
            String nombre1 = (String)modeloTabla.getValueAt(filaSeleccionada, 1);
            int anio1 = (Integer)modeloTabla.getValueAt(filaSeleccionada, 2);
            Materia mat = new Materia(idMateria,nombre1,anio1,true);
            Inscripcion insc = new Inscripcion(0,seleccionado,mat); 
            inscripcionD.guardarInscripcion(insc);
        } else {
            JOptionPane.showMessageDialog(null,"Debe seleccionar una materia");
        }
        
    }//GEN-LAST:event_jInscribirActionPerformed

    private void jAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnularActionPerformed
        int filaSeleccionada = jTablaMaterias.getSelectedRow();
        if (filaSeleccionada != -1){
            Alumno seleccionado =(Alumno)cBAlumnos.getSelectedItem();
            int idMateria = (Integer)modeloTabla.getValueAt(filaSeleccionada, 0);
            inscripcionD.borrarInscripcionMateriaAlumno(seleccionado.getId(), idMateria);
        } else {
            JOptionPane.showMessageDialog(null,"Debe seleccionar una materia");
        }
        

    }//GEN-LAST:event_jAnularActionPerformed

    private void jInscriptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInscriptosActionPerformed
        // TODO add your handling code here:
        jNoInscriptas.setSelected(false);
        jAnular.setEnabled(true);
        jInscribir.setEnabled(false);
        llenarTabla();
    }//GEN-LAST:event_jInscriptosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> cBAlumnos;
    private javax.swing.JButton jAnular;
    private javax.swing.JButton jInscribir;
    private javax.swing.JRadioButton jInscriptos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jNoInscriptas;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaMaterias;
    // End of variables declaration//GEN-END:variables
}
