
package vistas;

import controladores.AlumnoData;
import controladores.InscripcionData;
import controladores.MateriaData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.Inscripcion;
import modelo.Materia;

/**
 *
 * @author Giulietta
 */
public class VistasInscripciones extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private Inscripcion inscripcion = new Inscripcion();
    private InscripcionData inscripcionD = new InscripcionData();
    private AlumnoData alumnoD = new AlumnoData();
    private Materia materia = new Materia();
    private MateriaData materiaD = new MateriaData();
    private ArrayList<Inscripcion> inscriptos = new ArrayList();
    private ArrayList<Inscripcion> noinscriptos = new ArrayList();
    private ArrayList<Alumno> alumnos = new ArrayList();
    private ArrayList<Materia> materias = new ArrayList();
    /**
     * Creates new form VistasInscripciones
     */
    public VistasInscripciones() {
        initComponents();
        alumnos = alumnoD.listarAlumnos();
        encabezado();
        llenarComboBox();
    } 
    
    private void llenarComboBox(){
        for(Alumno a: alumnos){
            cBAlumnos.addItem(a);
        }
    }
    
    private void encabezado(){
        ArrayList<Object> columna = new ArrayList();
        columna.add("Código");
        columna.add("Nombre");
        columna.add("Año");
        for(Object c: columna){
            modeloTabla.addColumn(c);
        }
        jTablaMaterias.setModel(modeloTabla);
    }
    private void llenarTabla(){
        borrarFilas();
        Alumno seleccionado =(Alumno)cBAlumnos.getSelectedItem();
        if(jInscriptos.isSelected() == true){
            materias = inscripcionD.obtenerMateriasCursadas(seleccionado.getId());
            for(Materia a:materias){
            modeloTabla.addRow(new Object[]{a.getId_materia(),a.getNombre(),a.getAnio()});
            }
        }
        if(jNoInscriptas.isSelected() == true){
            materias = inscripcionD.obtenerMateriasNOCursadas(seleccionado.getId());
            for(Materia a:materias){
            modeloTabla.addRow(new Object[]{a.getId_materia(),a.getNombre(),a.getAnio()});
            }
        }
        
        
        
    }
    
    private void borrarFilas(){
        int fila = modeloTabla.getRowCount()-1;
        for(int i=fila; i>=0;i--){
            modeloTabla.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cBAlumnos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jInscriptos = new javax.swing.JRadioButton();
        jNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaMaterias = new javax.swing.JTable();
        jInscribir = new javax.swing.JButton();
        jAnular = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setMaximumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(450, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSalir.setBackground(new java.awt.Color(0, 102, 102));
        jSalir.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jSalir.setForeground(new java.awt.Color(255, 255, 255));
        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 372, 86, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Formulario de inscripción");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("ALUMNO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 58, -1, -1));

        cBAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(cBAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 52, 176, 32));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("LISTADO DE MATERIAS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 108, -1, -1));

        jInscriptos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jInscriptos.setForeground(new java.awt.Color(0, 102, 102));
        jInscriptos.setText("Inscriptas");
        jInscriptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInscriptosActionPerformed(evt);
            }
        });
        getContentPane().add(jInscriptos, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 144, -1, -1));

        jNoInscriptas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jNoInscriptas.setForeground(new java.awt.Color(0, 102, 102));
        jNoInscriptas.setText("No Inscriptas");
        jNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoInscriptasActionPerformed(evt);
            }
        });
        getContentPane().add(jNoInscriptas, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 144, -1, -1));

        jTablaMaterias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jTablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablaMaterias);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 184, 404, 153));

        jInscribir.setBackground(new java.awt.Color(0, 102, 102));
        jInscribir.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jInscribir.setForeground(new java.awt.Color(255, 255, 255));
        jInscribir.setText("Inscribir");
        jInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInscribirActionPerformed(evt);
            }
        });
        getContentPane().add(jInscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 372, -1, -1));

        jAnular.setBackground(new java.awt.Color(0, 102, 102));
        jAnular.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jAnular.setForeground(new java.awt.Color(255, 255, 255));
        jAnular.setText("Anular Inscripcion");
        jAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnularActionPerformed(evt);
            }
        });
        getContentPane().add(jAnular, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 372, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        dispose();

    }//GEN-LAST:event_jSalirActionPerformed

    private void cBAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBAlumnosActionPerformed
        jInscriptos.setSelected(false);
        jNoInscriptas.setSelected(false);
        jInscribir.setEnabled(false);
        jAnular.setEnabled(false);
        borrarFilas();
    }//GEN-LAST:event_cBAlumnosActionPerformed

    private void jNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoInscriptasActionPerformed
        jInscribir.setEnabled(true);
        jAnular.setEnabled(false);
        jInscriptos.setSelected(false);
        llenarTabla();
    }//GEN-LAST:event_jNoInscriptasActionPerformed

    private void jInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInscribirActionPerformed
        int filaSeleccionada = jTablaMaterias.getSelectedRow();
        if (filaSeleccionada != -1){
            Alumno seleccionado =(Alumno)cBAlumnos.getSelectedItem();
            int idMateria = (Integer)modeloTabla.getValueAt(filaSeleccionada, 0);
            String nombre1 = (String)modeloTabla.getValueAt(filaSeleccionada, 1);
            int anio1 = (Integer)modeloTabla.getValueAt(filaSeleccionada, 2);
            Materia mat = new Materia(idMateria,nombre1,anio1,true);
            Inscripcion insc = new Inscripcion(0,seleccionado,mat); 
            inscripcionD.guardarInscripcion(insc);
        } else {
            JOptionPane.showMessageDialog(null,"Debe seleccionar una materia");
        }
        
    }//GEN-LAST:event_jInscribirActionPerformed

    private void jAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnularActionPerformed
        int filaSeleccionada = jTablaMaterias.getSelectedRow();
        if (filaSeleccionada != -1){
            Alumno seleccionado =(Alumno)cBAlumnos.getSelectedItem();
            int idMateria = (Integer)modeloTabla.getValueAt(filaSeleccionada, 0);
            inscripcionD.borrarInscripcionMateriaAlumno(seleccionado.getId(), idMateria);
        } else {
            JOptionPane.showMessageDialog(null,"Debe seleccionar una materia");
        }
        

    }//GEN-LAST:event_jAnularActionPerformed

    private void jInscriptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInscriptosActionPerformed
        // TODO add your handling code here:
        jNoInscriptas.setSelected(false);
        jAnular.setEnabled(true);
        jInscribir.setEnabled(false);
        llenarTabla();
    }//GEN-LAST:event_jInscriptosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> cBAlumnos;
    private javax.swing.JButton jAnular;
    private javax.swing.JButton jInscribir;
    private javax.swing.JRadioButton jInscriptos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jNoInscriptas;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaMaterias;
    // End of variables declaration//GEN-END:variables
}
