/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import controladores.AlumnoData;
import controladores.InscripcionData;
import controladores.MateriaData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.Inscripcion;
import modelo.Materia;

/**
 *
 * @author Giulietta
 */
public class VistasInscripciones extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private Inscripcion inscripcion = new Inscripcion();
    private InscripcionData inscripcionD = new InscripcionData();
    private AlumnoData alumnoD = new AlumnoData();
    private Materia materia = new Materia();
    private MateriaData materiaD = new MateriaData();
    private ArrayList<Inscripcion> inscriptos = new ArrayList();
    private ArrayList<Inscripcion> noinscriptos = new ArrayList();
    private ArrayList<Alumno> alumnos = new ArrayList();
    private ArrayList<Materia> materias = new ArrayList();
    /**
     * Creates new form VistasInscripciones
     */
    public VistasInscripciones() {
        initComponents();
        alumnos = alumnoD.listarAlumnos();
        encabezado();
        llenarComboBox();
    } 
    
    private void llenarComboBox(){
        for(Alumno a: alumnos){
            cBAlumnos.addItem(a);
        }
    }
    
    private void encabezado(){
        ArrayList<Object> columna = new ArrayList();
        columna.add("Código");
        columna.add("Nombre");
        columna.add("Año");
        for(Object c: columna){
            modeloTabla.addColumn(c);
        }
        jTablaMaterias.setModel(modeloTabla);
    }
    private void llenarTabla(){
        borrarFilas();
        Alumno seleccionado =(Alumno)cBAlumnos.getSelectedItem();
        if(jInscriptos.isSelected() == true){
            materias = inscripcionD.obtenerMateriasCursadas(seleccionado.getId());
            for(Materia a:materias){
            modeloTabla.addRow(new Object[]{a.getId_materia(),a.getNombre(),a.getAnio()});
            }
        }
        if(jNoInscriptas.isSelected() == true){
            materias = inscripcionD.obtenerMateriasNOCursadas(seleccionado.getId());
            for(Materia a:materias){
            modeloTabla.addRow(new Object[]{a.getId_materia(),a.getNombre(),a.getAnio()});
            }
        }
        
        
        
    }
    
    private void borrarFilas(){
        int fila = modeloTabla.getRowCount()-1;
        for(int i=fila; i>=0;i--){
            modeloTabla.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cBAlumnos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jInscriptos = new javax.swing.JRadioButton();
        jNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaMaterias = new javax.swing.JTable();
        jInscribir = new javax.swing.JButton();
        jAnular = new javax.swing.JButton();

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("-FORMULARIO DE INSCRIPCION-");

        jLabel4.setText("ALUMNO");

        cBAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBAlumnosActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("LISTADO DE MATERIAS");

        jInscriptos.setText("Inscriptas");
        jInscriptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInscriptosActionPerformed(evt);
            }
        });

        jNoInscriptas.setText("No Inscriptas");
        jNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoInscriptasActionPerformed(evt);
            }
        });

        jTablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablaMaterias);

        jInscribir.setText("Inscribir");
        jInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInscribirActionPerformed(evt);
            }
        });

        jAnular.setText("Anular Inscripcion");
        jAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel4)
                        .addGap(56, 56, 56)
                        .addComponent(cBAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jInscribir)
                        .addGap(50, 50, 50)
                        .addComponent(jAnular)
                        .addGap(62, 62, 62)
                        .addComponent(jSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jInscriptos)
                            .addGap(111, 111, 111)
                            .addComponent(jNoInscriptas))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(jLabel3))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInscriptos)
                    .addComponent(jNoInscriptas))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInscribir)
                    .addComponent(jAnular)
                    .addComponent(jSalir))
                .addGap(223, 223, 223))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        dispose();

    }//GEN-LAST:event_jSalirActionPerformed

    private void cBAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBAlumnosActionPerformed
        jInscriptos.setSelected(false);
        jNoInscriptas.setSelected(false);
        jInscribir.setEnabled(false);
        jAnular.setEnabled(false);
        borrarFilas();
    }//GEN-LAST:event_cBAlumnosActionPerformed

    private void jNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoInscriptasActionPerformed
        jInscribir.setEnabled(true);
        jAnular.setEnabled(false);
        jInscriptos.setSelected(false);
        llenarTabla();
    }//GEN-LAST:event_jNoInscriptasActionPerformed

    private void jInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInscribirActionPerformed
        int filaSeleccionada = jTablaMaterias.getSelectedRow();
        if (filaSeleccionada != -1){
            Alumno seleccionado =(Alumno)cBAlumnos.getSelectedItem();
            int idMateria = (Integer)modeloTabla.getValueAt(filaSeleccionada, 0);
            String nombre1 = (String)modeloTabla.getValueAt(filaSeleccionada, 1);
            int anio1 = (Integer)modeloTabla.getValueAt(filaSeleccionada, 2);
            Materia mat = new Materia(idMateria,nombre1,anio1,true);
            Inscripcion insc = new Inscripcion(0,seleccionado,mat); 
            inscripcionD.guardarInscripcion(insc);
        } else {
            JOptionPane.showMessageDialog(null,"Debe seleccionar una materia");
        }
        
    }//GEN-LAST:event_jInscribirActionPerformed

    private void jAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnularActionPerformed
        int filaSeleccionada = jTablaMaterias.getSelectedRow();
        if (filaSeleccionada != -1){
            Alumno seleccionado =(Alumno)cBAlumnos.getSelectedItem();
            int idMateria = (Integer)modeloTabla.getValueAt(filaSeleccionada, 0);
            inscripcionD.borrarInscripcionMateriaAlumno(seleccionado.getId(), idMateria);
        } else {
            JOptionPane.showMessageDialog(null,"Debe seleccionar una materia");
        }
        

    }//GEN-LAST:event_jAnularActionPerformed

    private void jInscriptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInscriptosActionPerformed
        // TODO add your handling code here:
        jNoInscriptas.setSelected(false);
        jAnular.setEnabled(true);
        jInscribir.setEnabled(false);
        llenarTabla();
    }//GEN-LAST:event_jInscriptosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> cBAlumnos;
    private javax.swing.JComboBox<Alumno> cbAlumnos;
    private javax.swing.JButton jAnular;
    private javax.swing.JButton jInscribir;
    private javax.swing.JRadioButton jInscriptos;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jNoInscriptas;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaMaterias;
    // End of variables declaration//GEN-END:variables
}
