
package vistas;

import controladores.AlumnoData;
import java.sql.Date;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import modelo.Alumno;

/**
 *
 * @author Giulietta
 */
public class VistasEditarAlumno extends javax.swing.JInternalFrame {
    AlumnoData alumnoD = new AlumnoData();
    Alumno alumno = new Alumno();
    /**
     * Creates new form VistasEditarAlumno
     */
    public VistasEditarAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDCFecha = new com.toedter.calendar.JDateChooser();
        jNombre = new javax.swing.JTextField();
        jApellido = new javax.swing.JTextField();
        jDNI = new javax.swing.JTextField();
        jIdAlumno = new javax.swing.JTextField();
        JBuscarId = new javax.swing.JButton();
        jBuscarDni = new javax.swing.JButton();
        jNuevo = new javax.swing.JButton();
        jSalir = new javax.swing.JButton();
        jEliminar = new javax.swing.JButton();
        jActualizar = new javax.swing.JButton();
        jEstado = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Alumno");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Código Alumno:");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Apellido:");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("DNI:");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Fecha Nacimiento: ");

        jApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jApellidoActionPerformed(evt);
            }
        });

        JBuscarId.setBackground(new java.awt.Color(0, 102, 102));
        JBuscarId.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        JBuscarId.setForeground(new java.awt.Color(255, 255, 255));
        JBuscarId.setText("Buscar");
        JBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBuscarIdActionPerformed(evt);
            }
        });

        jBuscarDni.setBackground(new java.awt.Color(0, 102, 102));
        jBuscarDni.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jBuscarDni.setForeground(new java.awt.Color(255, 255, 255));
        jBuscarDni.setText("Buscar");
        jBuscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarDniActionPerformed(evt);
            }
        });

        jNuevo.setBackground(new java.awt.Color(0, 102, 102));
        jNuevo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jNuevo.setForeground(new java.awt.Color(255, 255, 255));
        jNuevo.setText("Nuevo");
        jNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNuevoActionPerformed(evt);
            }
        });

        jSalir.setBackground(new java.awt.Color(0, 102, 102));
        jSalir.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jSalir.setForeground(new java.awt.Color(255, 255, 255));
        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jEliminar.setBackground(new java.awt.Color(0, 102, 102));
        jEliminar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jEliminar.setText("Eliminar");
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });

        jActualizar.setBackground(new java.awt.Color(0, 102, 102));
        jActualizar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jActualizar.setText("Actualizar");
        jActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarActionPerformed(evt);
            }
        });

        jEstado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jEstado.setForeground(new java.awt.Color(0, 102, 102));
        jEstado.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel3)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jEstado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEliminar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBuscarId)
                            .addComponent(jEliminar))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4))
                    .addComponent(jApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBuscarDni))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6)))
                .addGap(32, 32, 32)
                .addComponent(jEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jActualizar)
                    .addComponent(jNuevo)
                    .addComponent(jSalir))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jApellidoActionPerformed

    private void JBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBuscarIdActionPerformed
        // TODO add your handling code here:
        try {
        int id = Integer.parseInt(jIdAlumno.getText());
        alumno = alumnoD.buscarAlumno(id);
        jNombre.setText(alumno.getNombre());
        jApellido.setText(alumno.getApellido());
        jDNI.setText(Integer.toString(alumno.getDni()));
        jDCFecha.setDate(Date.valueOf(alumno.getFecha_nacimiento()));
        jEstado.setSelected(alumno.isEstado());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error: Ingrese un id existente");
        }
        
    }//GEN-LAST:event_JBuscarIdActionPerformed

    private void jBuscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarDniActionPerformed
        // TODO add your handling code here:
        try {
        int dni = Integer.parseInt(jDNI.getText());
        alumno = alumnoD.buscarAlumnoporDni(dni);
        jIdAlumno.setText(Integer.toString(alumno.getId()));
        jNombre.setText(alumno.getNombre());
        jApellido.setText(alumno.getApellido());
        jDCFecha.setDate(Date.valueOf(alumno.getFecha_nacimiento()));
        jEstado.setSelected(alumno.isEstado());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error: Ingrese un DNI existente");
        }
    }//GEN-LAST:event_jBuscarDniActionPerformed

    private void jNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        
    }//GEN-LAST:event_jNuevoActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
        // TODO add your handling code here:
        try {
        int id = Integer.parseInt(jIdAlumno.getText());
        alumnoD.eliminarAlumno(id);
        limpiar();
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error: Ingrese un id existente");
        }
    }//GEN-LAST:event_jEliminarActionPerformed

    private void jActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarActionPerformed
        // TODO add your handling code here:
            alumno.setNombre(jNombre.getText());
            alumno.setApellido(jApellido.getText());
            alumno.setDni(Integer.parseInt(jDNI.getText()));
            alumno.setFecha_nacimiento(jDCFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            alumno.setEstado(jEstado.isSelected());
            alumnoD.actualizarAlumno(alumno);
       
        
    }//GEN-LAST:event_jActualizarActionPerformed
    private void limpiar(){
        jIdAlumno.setText("");
        jNombre.setText("");
        jApellido.setText("");
        jDNI.setText("");
        jDCFecha.setDate(null);
        jEstado.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBuscarId;
    private javax.swing.JButton jActualizar;
    private javax.swing.JTextField jApellido;
    private javax.swing.JButton jBuscarDni;
    private com.toedter.calendar.JDateChooser jDCFecha;
    private javax.swing.JTextField jDNI;
    private javax.swing.JButton jEliminar;
    private javax.swing.JRadioButton jEstado;
    private javax.swing.JTextField jIdAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNombre;
    private javax.swing.JButton jNuevo;
    private javax.swing.JButton jSalir;
    // End of variables declaration//GEN-END:variables
}
